app:
  name: "goDefaultCli"
  mode: "dev"
  port: 8080
log:
  level: "debug"
  filename: "go_default_cli.log"
  max_size: 200
  max_age: 30
  max_backips: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: ""
  dbname: "sql_test"
redis:
  host: "127.0.0.1"
  port: 16379
  db: 0